### ISSUE TITLE
pesquisa de projetos correlatos

### ISSUE THREAD

**Issue by henrylog10** [Projetos-III-UFPA-2024-4/Zephyrus#15]
achar soluções existentes no mercado e no meio cíentifico

**Comment by henrylog10** [comment]
https://www.semanticscholar.org/paper/Melldia%3A-Aprimorando-o-Controle-do-Diabetes-por-de-Estevam-Pereira/9b8691524a1f38b3b8c61158a212a030f04fd770#extracted

https://pesquisaparainovacao.fapesp.br/plataforma_auxilia_pacientes_no_controle_e_prevencao_de_complicacoes_desencadeadas_pelo_diabetes/2844

https://chatgpt.com/share/675877ed-3f80-800f-ae76-80f1934214d5

**Comment by henrylog10** [comment]
em suma, existem muitas aplicações com a mesma finalidade, o objetivo do time seria criar uma espécie de extensão a estas soluções
(ainda em analise)

**Comment by S4ulo-Th3us** [comment]
![Image](https://github.com/user-attachments/assets/7f826c63-652e-406b-abc1-5ae528f5a4ce)

![Image](https://github.com/user-attachments/assets/9d02332e-4236-4433-bc12-86e3c11c8cf7)


Soluções existentes no mercado.

Ambas voltadas para o monitoramento e controle de diabetes, mas ambas possuem um interface pouco intuitiva e com o registro de acompanhamento sendo preenchido manualmente pelo usuário.
