### ISSUE TITLE
produção do terceiro slide do pitch

### ISSUE THREAD

**Issue by henrylog10** [Projetos-III-UFPA-2024-4/Zephyrus#17]
TRL nivél 3

- > IA que reconhece quantidade de carbo(função crítica);
- > Aconselhamento nutricional(quantidade nas porções);
- > Gerenciamento de perfis e contas(estilo netflix)
- > Histórico alimentar dos perfis

**Comment by S4ulo-Th3us** [comment]
✅IA que reconhece quantidade de carbo(função crítica);

**Comment by S4ulo-Th3us** [comment]
✅ Aconselhamento nutricional(quantidade nas porções);
